# Generated by Django 4.1.7 on 2023-12-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='mark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='roundoff',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='tax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='types',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
