# Generated by Django 4.1.7 on 2024-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_pricelist_date_alter_pricelist_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
